### PR TITLE
Prettify standard

### PR DESCRIPTION
**Pull request by cyrilchapon**
Improving https://github.com/derhuerst/parse-gml-polygon/commit/c0ad936f4d232ebcaa4b71c8e0093431cc26b357

### CODE REVIEW

**Comment by derhuerst** [comment]
Not too keen about the additional weight in tooling, but happy to merge this if you think it is worth it.

**Comment by cyrilchapon** [comment]
> Not too keen about the additional weight in tooling

That's my case also. I basically no-go everything that is not simple and light for tools.

But the downside of weight for snazzy (once, at install) is **really** worth the time you save when reading standard output (like 30 times each time you iterate on a feature)

**Comment by derhuerst** [comment]
You don't trust `standard --fix`? Because that saves you a lot of reading linting logs as well.

**Comment by cyrilchapon** [comment]
Yes I do. I actually prefer auto standard (without fix) inside IDEs to show errors.

I guess you too don't npm run lint manually, but maybe we'll put some hooks (git/npm). We also want new maintainers to have great standard output

**Comment by derhuerst** [comment]
To add even more tooling, we can add [`husky`](https://npmjs.com/package/husky). 😉

**Comment by cyrilchapon** [comment]
Yep I use it in production in here.

But I was mentaly struggling for this lib as "where should we lint" ?

- prepublish (npm) ?
- precommit (git) ?
- prepush (git) ?

**Comment by derhuerst** [comment]
I think `precommit` is infantilising devs. I want to be able to `-p`-commit changes quickly and amend later. I'd propose `prepush`

**Comment by highsource** [comment]
Yesterday I've `npm run lint` a few times and happily corrected all the reported errors manually on my (local) branch. So thank you for adding linting, worked for me. :)

**Comment by derhuerst** [comment]
@cyrilchapon Just be clear: I wouldn't add `standard --fix` as `prepush`, definitely just `standard | snazzy`.

**Pull request merged**
